spring:
  config:
    activate:
      on-profile: prod

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD:}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 0
      connection-timeout: 30000
      validation-timeout: 5000
      max-lifetime: 240000
      idle-timeout: 60000
      keepalive-time: 60000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

cookie:
  secure: true
  same-site: None
  domain: ${COOKIE_DOMAIN:.mmm3.click}

logging:
  level:
    root: INFO
    com.syncnote: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
    org.hibernate.orm.jdbc.extract: WARN
    org.springframework.transaction.interceptor: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
